"""initial schema

Revision ID: 036c7c8f6d6b
Revises: 
Create Date: 2026-02-12 23:34:09.959472
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '036c7c8f6d6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('antibody_clone', sa.String(length=100), nullable=True),
    sa.Column('fda_approved', sa.Boolean(), nullable=True),
    sa.Column('companion_dx_for', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('biomarker_names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('biomarkers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gene_symbol', sa.String(length=50), nullable=True),
    sa.Column('ensembl_id', sa.String(length=50), nullable=True),
    sa.Column('uniprot_id', sa.String(length=20), nullable=True),
    sa.Column('search_terms', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('civic_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('civic_id', sa.Integer(), nullable=False),
    sa.Column('gene_name', sa.String(length=100), nullable=True),
    sa.Column('variant_name', sa.String(length=200), nullable=True),
    sa.Column('disease_name', sa.String(length=200), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=True),
    sa.Column('evidence_level', sa.String(length=10), nullable=True),
    sa.Column('evidence_direction', sa.String(length=50), nullable=True),
    sa.Column('significance', sa.String(length=100), nullable=True),
    sa.Column('drugs', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('source_pmid', sa.String(length=20), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('civic_id')
    )
    op.create_table('cutoff_trends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('biomarker_name', sa.String(length=100), nullable=False),
    sa.Column('tumor_type', sa.String(length=100), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('cutoff_value', sa.Float(), nullable=True),
    sa.Column('cutoff_unit', sa.String(length=100), nullable=True),
    sa.Column('trial_count', sa.Integer(), nullable=True),
    sa.Column('dominant_assay', sa.String(length=200), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biomarker_name', 'tumor_type', 'year', 'cutoff_unit', name='uq_cutoff_trend')
    )
    op.create_table('gwas_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rs_id', sa.String(length=30), nullable=False),
    sa.Column('gene', sa.String(length=100), nullable=True),
    sa.Column('trait_name', sa.String(length=300), nullable=True),
    sa.Column('p_value', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('odds_ratio', sa.Float(), nullable=True),
    sa.Column('risk_allele', sa.String(length=50), nullable=True),
    sa.Column('population', sa.String(length=100), nullable=True),
    sa.Column('pubmed_id', sa.String(length=20), nullable=True),
    sa.Column('study_title', sa.Text(), nullable=True),
    sa.Column('biomarker_relevance', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rs_id', 'trait_name', name='uq_gwas_rs_trait')
    )
    op.create_table('indications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('ct_gov_terms', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('efo_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('open_targets_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_ensembl_id', sa.String(length=50), nullable=False),
    sa.Column('target_symbol', sa.String(length=50), nullable=False),
    sa.Column('target_name', sa.String(length=200), nullable=True),
    sa.Column('disease_efo_id', sa.String(length=50), nullable=False),
    sa.Column('disease_name', sa.String(length=200), nullable=True),
    sa.Column('association_score', sa.Float(), nullable=True),
    sa.Column('datatype_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_ensembl_id', 'disease_efo_id', name='uq_ot_target_disease')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('indication', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pubmed_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pmid', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('journal', sa.String(length=300), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('mesh_terms', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('biomarker_mentions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('indication_mentions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pmid')
    )
    op.create_table('trials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nct_id', sa.String(length=20), nullable=False),
    sa.Column('brief_title', sa.Text(), nullable=False),
    sa.Column('official_title', sa.Text(), nullable=True),
    sa.Column('overall_status', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=True),
    sa.Column('phases_raw', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('study_type', sa.String(length=50), nullable=True),
    sa.Column('lead_sponsor_name', sa.String(length=300), nullable=True),
    sa.Column('lead_sponsor_class', sa.String(length=50), nullable=True),
    sa.Column('collaborators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('start_year', sa.SmallInteger(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('primary_completion', sa.Date(), nullable=True),
    sa.Column('enrollment_count', sa.Integer(), nullable=True),
    sa.Column('enrollment_type', sa.String(length=30), nullable=True),
    sa.Column('brief_summary', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('conditions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('interventions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('secondary_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allocation', sa.String(length=50), nullable=True),
    sa.Column('intervention_model', sa.String(length=50), nullable=True),
    sa.Column('primary_purpose', sa.String(length=50), nullable=True),
    sa.Column('masking', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('minimum_age', sa.String(length=30), nullable=True),
    sa.Column('maximum_age', sa.String(length=30), nullable=True),
    sa.Column('detected_tumor_type', sa.String(length=100), nullable=True),
    sa.Column('detected_setting', sa.String(length=50), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nlp_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nlp_version', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trials_conditions', 'trials', ['conditions'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_trials_lead_sponsor_class'), 'trials', ['lead_sponsor_class'], unique=False)
    op.create_index(op.f('ix_trials_lead_sponsor_name'), 'trials', ['lead_sponsor_name'], unique=False)
    op.create_index(op.f('ix_trials_nct_id'), 'trials', ['nct_id'], unique=True)
    op.create_index(op.f('ix_trials_overall_status'), 'trials', ['overall_status'], unique=False)
    op.create_index(op.f('ix_trials_phase'), 'trials', ['phase'], unique=False)
    op.create_index(op.f('ix_trials_start_year'), 'trials', ['start_year'], unique=False)
    op.create_table('trial_biomarkers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=False),
    sa.Column('biomarker_id', sa.Integer(), nullable=False),
    sa.Column('biomarker_name', sa.String(length=100), nullable=False),
    sa.Column('cutoff_value', sa.String(length=100), nullable=True),
    sa.Column('cutoff_unit', sa.String(length=100), nullable=True),
    sa.Column('cutoff_operator', sa.String(length=20), nullable=True),
    sa.Column('cutoff_raw_text', sa.Text(), nullable=True),
    sa.Column('assay_name', sa.String(length=200), nullable=True),
    sa.Column('assay_manufacturer', sa.String(length=200), nullable=True),
    sa.Column('assay_platform', sa.String(length=100), nullable=True),
    sa.Column('companion_diagnostic', sa.Boolean(), nullable=True),
    sa.Column('biomarker_role', sa.String(length=50), nullable=True),
    sa.Column('biomarker_context', sa.String(length=200), nullable=True),
    sa.Column('tumor_type', sa.String(length=100), nullable=True),
    sa.Column('therapeutic_setting', sa.String(length=50), nullable=True),
    sa.Column('extraction_source', sa.String(length=50), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('raw_snippet', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['biomarker_id'], ['biomarkers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trial_id', 'biomarker_id', 'cutoff_value', 'cutoff_unit', name='uq_trial_biomarker_cutoff')
    )
    op.create_index(op.f('ix_trial_biomarkers_assay_name'), 'trial_biomarkers', ['assay_name'], unique=False)
    op.create_index(op.f('ix_trial_biomarkers_biomarker_id'), 'trial_biomarkers', ['biomarker_id'], unique=False)
    op.create_index(op.f('ix_trial_biomarkers_biomarker_name'), 'trial_biomarkers', ['biomarker_name'], unique=False)
    op.create_index(op.f('ix_trial_biomarkers_biomarker_role'), 'trial_biomarkers', ['biomarker_role'], unique=False)
    op.create_index(op.f('ix_trial_biomarkers_therapeutic_setting'), 'trial_biomarkers', ['therapeutic_setting'], unique=False)
    op.create_index(op.f('ix_trial_biomarkers_trial_id'), 'trial_biomarkers', ['trial_id'], unique=False)
    op.create_index(op.f('ix_trial_biomarkers_tumor_type'), 'trial_biomarkers', ['tumor_type'], unique=False)
    op.create_table('trial_indications',
    sa.Column('trial_id', sa.Integer(), nullable=False),
    sa.Column('indication_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indication_id'], ['indications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trial_id', 'indication_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trial_indications')
    op.drop_index(op.f('ix_trial_biomarkers_tumor_type'), table_name='trial_biomarkers')
    op.drop_index(op.f('ix_trial_biomarkers_trial_id'), table_name='trial_biomarkers')
    op.drop_index(op.f('ix_trial_biomarkers_therapeutic_setting'), table_name='trial_biomarkers')
    op.drop_index(op.f('ix_trial_biomarkers_biomarker_role'), table_name='trial_biomarkers')
    op.drop_index(op.f('ix_trial_biomarkers_biomarker_name'), table_name='trial_biomarkers')
    op.drop_index(op.f('ix_trial_biomarkers_biomarker_id'), table_name='trial_biomarkers')
    op.drop_index(op.f('ix_trial_biomarkers_assay_name'), table_name='trial_biomarkers')
    op.drop_table('trial_biomarkers')
    op.drop_index(op.f('ix_trials_start_year'), table_name='trials')
    op.drop_index(op.f('ix_trials_phase'), table_name='trials')
    op.drop_index(op.f('ix_trials_overall_status'), table_name='trials')
    op.drop_index(op.f('ix_trials_nct_id'), table_name='trials')
    op.drop_index(op.f('ix_trials_lead_sponsor_name'), table_name='trials')
    op.drop_index(op.f('ix_trials_lead_sponsor_class'), table_name='trials')
    op.drop_index('idx_trials_conditions', table_name='trials', postgresql_using='gin')
    op.drop_table('trials')
    op.drop_table('pubmed_articles')
    op.drop_table('pipeline_runs')
    op.drop_table('open_targets_associations')
    op.drop_table('indications')
    op.drop_table('gwas_associations')
    op.drop_table('cutoff_trends')
    op.drop_table('civic_evidence')
    op.drop_table('biomarkers')
    op.drop_table('assays')
    # ### end Alembic commands ###
