"""add_ot_druggability_tables

Revision ID: b5fdf825c285
Revises: 036c7c8f6d6b
Create Date: 2026-02-15 14:39:45.918546
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b5fdf825c285'
down_revision: Union[str, None] = '036c7c8f6d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ot_cancer_biomarker_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('biomarker_symbol', sa.String(length=50), nullable=False),
    sa.Column('ensembl_id', sa.String(length=50), nullable=False),
    sa.Column('drug_name', sa.String(length=300), nullable=True),
    sa.Column('confidence', sa.String(length=100), nullable=True),
    sa.Column('disease_from_source', sa.String(length=300), nullable=True),
    sa.Column('indication_name', sa.String(length=100), nullable=False),
    sa.Column('efo_id', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ot_cancer_biomarker_evidence_biomarker_symbol'), 'ot_cancer_biomarker_evidence', ['biomarker_symbol'], unique=False)
    op.create_index(op.f('ix_ot_cancer_biomarker_evidence_indication_name'), 'ot_cancer_biomarker_evidence', ['indication_name'], unique=False)
    op.create_table('ot_known_drugs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('biomarker_symbol', sa.String(length=50), nullable=False),
    sa.Column('ensembl_id', sa.String(length=50), nullable=False),
    sa.Column('drug_name', sa.String(length=300), nullable=False),
    sa.Column('drug_chembl_id', sa.String(length=50), nullable=True),
    sa.Column('drug_type', sa.String(length=100), nullable=True),
    sa.Column('max_phase', sa.Float(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('year_approved', sa.SmallInteger(), nullable=True),
    sa.Column('mechanism_of_action', sa.Text(), nullable=True),
    sa.Column('disease_name', sa.String(length=300), nullable=True),
    sa.Column('disease_efo_id', sa.String(length=50), nullable=True),
    sa.Column('indication_name', sa.String(length=100), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ensembl_id', 'drug_chembl_id', 'disease_efo_id', name='uq_ot_drug_target_disease')
    )
    op.create_index(op.f('ix_ot_known_drugs_biomarker_symbol'), 'ot_known_drugs', ['biomarker_symbol'], unique=False)
    op.create_index(op.f('ix_ot_known_drugs_indication_name'), 'ot_known_drugs', ['indication_name'], unique=False)
    op.create_table('ot_target_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('biomarker_symbol', sa.String(length=50), nullable=False),
    sa.Column('ensembl_id', sa.String(length=50), nullable=False),
    sa.Column('indication_name', sa.String(length=100), nullable=False),
    sa.Column('efo_id', sa.String(length=50), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('drug_score', sa.Float(), nullable=True),
    sa.Column('cancer_biomarker_score', sa.Float(), nullable=True),
    sa.Column('cancer_gene_census_score', sa.Float(), nullable=True),
    sa.Column('intogen_score', sa.Float(), nullable=True),
    sa.Column('literature_score', sa.Float(), nullable=True),
    sa.Column('sm_tractable', sa.Boolean(), nullable=True),
    sa.Column('sm_has_approved_drug', sa.Boolean(), nullable=True),
    sa.Column('ab_tractable', sa.Boolean(), nullable=True),
    sa.Column('ab_has_approved_drug', sa.Boolean(), nullable=True),
    sa.Column('protac_tractable', sa.Boolean(), nullable=True),
    sa.Column('unique_drugs', sa.Integer(), nullable=True),
    sa.Column('approved_drug_count', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ensembl_id', 'efo_id', name='uq_ot_assoc_target_disease')
    )
    op.create_index(op.f('ix_ot_target_associations_biomarker_symbol'), 'ot_target_associations', ['biomarker_symbol'], unique=False)
    op.create_index(op.f('ix_ot_target_associations_indication_name'), 'ot_target_associations', ['indication_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ot_target_associations_indication_name'), table_name='ot_target_associations')
    op.drop_index(op.f('ix_ot_target_associations_biomarker_symbol'), table_name='ot_target_associations')
    op.drop_table('ot_target_associations')
    op.drop_index(op.f('ix_ot_known_drugs_indication_name'), table_name='ot_known_drugs')
    op.drop_index(op.f('ix_ot_known_drugs_biomarker_symbol'), table_name='ot_known_drugs')
    op.drop_table('ot_known_drugs')
    op.drop_index(op.f('ix_ot_cancer_biomarker_evidence_indication_name'), table_name='ot_cancer_biomarker_evidence')
    op.drop_index(op.f('ix_ot_cancer_biomarker_evidence_biomarker_symbol'), table_name='ot_cancer_biomarker_evidence')
    op.drop_table('ot_cancer_biomarker_evidence')
    # ### end Alembic commands ###
