"""fix_ot_drugs_unique_constraint

Revision ID: ef1f4e3e547a
Revises: b5fdf825c285
Create Date: 2026-02-15 14:46:47.982188
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ef1f4e3e547a'
down_revision: Union[str, None] = 'b5fdf825c285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ot_drug_target_disease'), 'ot_known_drugs', type_='unique')
    op.create_unique_constraint('uq_ot_drug_target_disease_ind', 'ot_known_drugs', ['ensembl_id', 'drug_chembl_id', 'disease_efo_id', 'indication_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ot_drug_target_disease_ind', 'ot_known_drugs', type_='unique')
    op.create_unique_constraint(op.f('uq_ot_drug_target_disease'), 'ot_known_drugs', ['ensembl_id', 'drug_chembl_id', 'disease_efo_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
