"""Seed data for indications, biomarkers, and assays."""

INDICATIONS = [
    {
        "name": "NSCLC",
        "display_name": "Non-Small Cell Lung Cancer",
        "ct_gov_terms": ["non-small cell lung cancer", "NSCLC"],
        "efo_id": "EFO_0003060",
    },
    {
        "name": "Breast Cancer",
        "display_name": "Breast Cancer",
        "ct_gov_terms": ["breast cancer", "breast carcinoma"],
        "efo_id": "EFO_0000305",
    },
    {
        "name": "Melanoma",
        "display_name": "Melanoma",
        "ct_gov_terms": ["melanoma"],
        "efo_id": "EFO_0000389",
    },
    {
        "name": "Colorectal Cancer",
        "display_name": "Colorectal Cancer",
        "ct_gov_terms": ["colorectal cancer", "colon cancer", "rectal cancer"],
        "efo_id": "EFO_0005842",
    },
    {
        "name": "Gastric Cancer",
        "display_name": "Gastric Cancer",
        "ct_gov_terms": ["gastric cancer", "stomach cancer"],
        "efo_id": "EFO_0000178",
    },
]

BIOMARKERS = [
    {"name": "PD-L1", "aliases": ["CD274", "B7-H1", "PDL1"], "category": "Predictive",
     "description": "Programmed death-ligand 1, immune checkpoint protein.",
     "gene_symbol": "CD274", "ensembl_id": "ENSG00000120217", "uniprot_id": "Q9NZQ7",
     "search_terms": ["pd-l1", "pdl1", "cd274", "pembrolizumab", "nivolumab", "atezolizumab", "durvalumab", "avelumab", "cemiplimab"]},
    {"name": "TMB", "aliases": ["Tumor Mutational Burden", "TMB-H"], "category": "Predictive",
     "description": "Total number of somatic mutations per megabase.",
     "gene_symbol": "N/A", "ensembl_id": None, "uniprot_id": None,
     "search_terms": ["tmb", "tumor mutational burden", "mutational load", "tmb-h"]},
    {"name": "MSI", "aliases": ["Microsatellite Instability", "MSI-H", "dMMR"], "category": "Predictive",
     "description": "Condition of genetic hypermutability due to impaired DNA mismatch repair.",
     "gene_symbol": "MLH1/MSH2/MSH6/PMS2", "ensembl_id": None, "uniprot_id": None,
     "search_terms": ["msi-h", "msi", "dmmr", "pmmr", "microsatellite", "mismatch repair", "mmr deficient"]},
    {"name": "HER2", "aliases": ["ERBB2", "neu"], "category": "Predictive",
     "description": "Human epidermal growth factor receptor 2.",
     "gene_symbol": "ERBB2", "ensembl_id": "ENSG00000141736", "uniprot_id": "P04626",
     "search_terms": ["her2", "erbb2", "trastuzumab", "her2-low", "her2-ultralow", "t-dxd", "t-dm1", "pertuzumab", "tucatinib"]},
    {"name": "EGFR", "aliases": ["ErbB-1", "HER1"], "category": "Predictive",
     "description": "Epidermal growth factor receptor, commonly mutated in NSCLC.",
     "gene_symbol": "EGFR", "ensembl_id": "ENSG00000146648", "uniprot_id": "P00533",
     "search_terms": ["egfr", "osimertinib", "erlotinib", "gefitinib", "amivantamab", "lazertinib", "exon 19", "l858r", "t790m", "exon 20"]},
    {"name": "ALK", "aliases": ["ALK fusion", "EML4-ALK"], "category": "Predictive",
     "description": "Anaplastic lymphoma kinase rearrangements.",
     "gene_symbol": "ALK", "ensembl_id": "ENSG00000171094", "uniprot_id": "Q9UM73",
     "search_terms": ["alk fusion", "alk rearrangement", "alk positive", "eml4-alk", "alectinib", "lorlatinib", "crizotinib", "ceritinib", "brigatinib"]},
    {"name": "BRCA1/2", "aliases": ["BRCA1", "BRCA2", "HRD"], "category": "Predictive",
     "description": "BRCA gene mutations associated with homologous recombination deficiency.",
     "gene_symbol": "BRCA1/BRCA2", "ensembl_id": "ENSG00000012048", "uniprot_id": None,
     "search_terms": ["brca", "brca1", "brca2", "olaparib", "rucaparib", "niraparib", "talazoparib", "parp", "hrd", "homologous recombination"]},
    {"name": "KRAS", "aliases": ["KRAS G12C", "KRAS G12D"], "category": "Predictive",
     "description": "Kirsten rat sarcoma viral oncogene homolog mutations.",
     "gene_symbol": "KRAS", "ensembl_id": "ENSG00000133703", "uniprot_id": "P01116",
     "search_terms": ["kras", "sotorasib", "adagrasib", "g12c", "g12d", "g12v"]},
    {"name": "BRAF", "aliases": ["BRAF V600E", "BRAF V600K"], "category": "Predictive",
     "description": "B-Raf proto-oncogene mutations.",
     "gene_symbol": "BRAF", "ensembl_id": "ENSG00000157764", "uniprot_id": "P15056",
     "search_terms": ["braf", "v600e", "v600k", "vemurafenib", "dabrafenib", "encorafenib", "cobimetinib", "trametinib", "binimetinib"]},
    {"name": "NTRK", "aliases": ["NTRK fusion", "TRK"], "category": "Predictive",
     "description": "Neurotrophic tyrosine receptor kinase gene fusions.",
     "gene_symbol": "NTRK1/2/3", "ensembl_id": None, "uniprot_id": None,
     "search_terms": ["ntrk", "trk fusion", "larotrectinib", "entrectinib", "ntrk1", "ntrk2", "ntrk3"]},
    {"name": "ctDNA", "aliases": ["Circulating Tumor DNA", "cfDNA"], "category": "Monitoring",
     "description": "Cell-free tumor DNA fragments in blood for MRD detection.",
     "gene_symbol": "N/A", "ensembl_id": None, "uniprot_id": None,
     "search_terms": ["ctdna", "circulating tumor dna", "cell-free dna", "cfdna", "liquid biopsy", "mrd", "minimal residual disease"]},
    {"name": "TILs", "aliases": ["Tumor-Infiltrating Lymphocytes", "sTILs"], "category": "Prognostic",
     "description": "Immune cells present within the tumor microenvironment.",
     "gene_symbol": None, "ensembl_id": None, "uniprot_id": None,
     "search_terms": ["tumor infiltrating lymphocytes", "tils", "til therapy", "stils"]},
    {"name": "ER", "aliases": ["Estrogen Receptor", "ER+", "ESR1"], "category": "Predictive",
     "description": "Estrogen receptor expression for endocrine therapy selection.",
     "gene_symbol": "ESR1", "ensembl_id": "ENSG00000091831", "uniprot_id": "P03372",
     "search_terms": ["estrogen receptor", "er-positive", "er+", "esr1", "er positive"]},
    {"name": "PR", "aliases": ["Progesterone Receptor", "PR+", "PGR"], "category": "Predictive",
     "description": "Progesterone receptor expression.",
     "gene_symbol": "PGR", "ensembl_id": "ENSG00000082175", "uniprot_id": "P06401",
     "search_terms": ["progesterone receptor", "pr-positive", "pr+", "pgr", "pr positive"]},
    {"name": "PIK3CA", "aliases": ["PI3K", "PIK3CA mutation"], "category": "Predictive",
     "description": "PIK3CA mutations activate PI3K/AKT pathway.",
     "gene_symbol": "PIK3CA", "ensembl_id": "ENSG00000121879", "uniprot_id": "P42336",
     "search_terms": ["pik3ca", "pi3k", "alpelisib", "pi3k inhibitor"]},
    {"name": "Ki-67", "aliases": ["Ki67", "MIB-1", "Proliferation Index"], "category": "Prognostic",
     "description": "Nuclear protein marker of cell proliferation.",
     "gene_symbol": "MKI67", "ensembl_id": "ENSG00000148773", "uniprot_id": "P46013",
     "search_terms": ["ki-67", "ki67", "mib-1", "proliferation index"]},
]

ASSAYS = [
    {"name": "22C3 pharmDx", "manufacturer": "Dako/Agilent", "platform": "IHC", "antibody_clone": "22C3",
     "fda_approved": True, "companion_dx_for": ["Pembrolizumab (NSCLC, HNSCC, Urothelial, Gastric, Cervical, TNBC)"], "biomarker_names": ["PD-L1"]},
    {"name": "28-8 pharmDx", "manufacturer": "Dako/Agilent", "platform": "IHC", "antibody_clone": "28-8",
     "fda_approved": True, "companion_dx_for": ["Nivolumab (Melanoma, NSCLC)"], "biomarker_names": ["PD-L1"]},
    {"name": "SP142", "manufacturer": "Ventana/Roche", "platform": "IHC", "antibody_clone": "SP142",
     "fda_approved": True, "companion_dx_for": ["Atezolizumab (TNBC, NSCLC, Urothelial)"], "biomarker_names": ["PD-L1"]},
    {"name": "SP263", "manufacturer": "Ventana/Roche", "platform": "IHC", "antibody_clone": "SP263",
     "fda_approved": True, "companion_dx_for": ["Durvalumab (Urothelial)"], "biomarker_names": ["PD-L1"]},
    {"name": "73-10", "manufacturer": "Dako/Agilent", "platform": "IHC", "antibody_clone": "73-10",
     "fda_approved": True, "companion_dx_for": ["Cemiplimab (Cervical)"], "biomarker_names": ["PD-L1"]},
    {"name": "FoundationOne CDx", "manufacturer": "Foundation Medicine", "platform": "NGS (324 genes)",
     "fda_approved": True, "companion_dx_for": ["Multiple targeted therapies", "TMB-H (Pembrolizumab)"],
     "biomarker_names": ["TMB", "MSI", "BRCA1/2", "EGFR", "ALK", "KRAS", "BRAF", "NTRK"]},
    {"name": "FoundationOne Liquid CDx", "manufacturer": "Foundation Medicine", "platform": "ctDNA NGS",
     "fda_approved": True, "companion_dx_for": ["Blood-based TMB", "EGFR", "ALK", "BRCA"],
     "biomarker_names": ["TMB", "EGFR", "ALK", "BRCA1/2", "ctDNA"]},
    {"name": "cobas EGFR Mutation Test v2", "manufacturer": "Roche", "platform": "PCR",
     "fda_approved": True, "companion_dx_for": ["Osimertinib", "Erlotinib", "Gefitinib"], "biomarker_names": ["EGFR"]},
    {"name": "Ventana ALK (D5F3)", "manufacturer": "Ventana/Roche", "platform": "IHC", "antibody_clone": "D5F3",
     "fda_approved": True, "companion_dx_for": ["Alectinib", "Crizotinib", "Ceritinib"], "biomarker_names": ["ALK"]},
    {"name": "BRACAnalysis CDx", "manufacturer": "Myriad Genetics", "platform": "PCR/Sequencing",
     "fda_approved": True, "companion_dx_for": ["Olaparib (Breast, Ovarian, Pancreatic, Prostate)", "Rucaparib (Ovarian, Prostate)"],
     "biomarker_names": ["BRCA1/2"]},
    {"name": "HercepTest", "manufacturer": "Dako/Agilent", "platform": "IHC", "antibody_clone": "Various",
     "fda_approved": True, "companion_dx_for": ["Trastuzumab", "T-DM1", "T-DXd", "Pertuzumab"], "biomarker_names": ["HER2"]},
    {"name": "therascreen KRAS RGQ PCR", "manufacturer": "Qiagen", "platform": "PCR",
     "fda_approved": True, "companion_dx_for": ["Sotorasib"], "biomarker_names": ["KRAS"]},
    {"name": "TSO500", "manufacturer": "Illumina", "platform": "NGS (523 genes)",
     "fda_approved": True, "companion_dx_for": ["TMB assessment"],
     "biomarker_names": ["TMB", "MSI", "EGFR", "BRAF", "KRAS", "NTRK"]},
    {"name": "Signatera", "manufacturer": "Natera", "platform": "ctDNA (tumor-informed PCR)",
     "fda_approved": False, "companion_dx_for": [], "biomarker_names": ["ctDNA"]},
    {"name": "Guardant360 CDx", "manufacturer": "Guardant Health", "platform": "ctDNA NGS (74 genes)",
     "fda_approved": True, "companion_dx_for": ["Osimertinib (EGFR T790M)", "Amivantamab (EGFR Exon20ins)"],
     "biomarker_names": ["EGFR", "KRAS", "ctDNA"]},
    {"name": "cobas 4800 BRAF V600", "manufacturer": "Roche", "platform": "PCR",
     "fda_approved": True, "companion_dx_for": ["Vemurafenib", "Cobimetinib"], "biomarker_names": ["BRAF"]},
    {"name": "THxID BRAF Kit", "manufacturer": "bioMerieux", "platform": "PCR",
     "fda_approved": True, "companion_dx_for": ["Dabrafenib", "Trametinib"], "biomarker_names": ["BRAF"]},
    {"name": "MSI by PCR (Promega)", "manufacturer": "Promega", "platform": "PCR (BAT-25, BAT-26, NR-21, NR-24, MONO-27)",
     "fda_approved": False, "companion_dx_for": [], "biomarker_names": ["MSI"]},
]
